listen=YES
listen_ipv6=NO
anonymous_enable=NO
local_enable=YES
write_enable=YES
local_umask=022
dirmessage_enable=YES
use_localtime=YES
xferlog_enable=YES
connect_from_port_20=YES
chroot_local_user=YES
allow_writeable_chroot=YES
secure_chroot_dir=/var/run/vsftpd/empty
pam_service_name=vsftpd

# TLS explicito (FTPS)
ssl_enable=YES
rsa_cert_file=/etc/ssl/certs/servidor.crt
rsa_private_key_file=/etc/ssl/private/servidor.key
force_local_logins_ssl=YES
force_local_data_ssl=YES
ssl_sslv2=NO
ssl_sslv3=NO
ssl_tlsv1=NO
ssl_ciphers=HIGH
require_ssl_reuse=NO

# Modo pasivo (coherente con las reglas de UFW)
pasv_enable=YES
pasv_min_port=50000
pasv_max_port=50010
pasv_address=192.168.56.3
